### PR TITLE
Add dependency management

### PR DESCRIPTION
**Pull request by zgalor**
Add dep and glog package to vendor

### CODE REVIEW

**Comment by zgalor** [comment]
@jhernand @moolitayer PTAL

**Comment by jhernand** [comment]
Why is this needed? In theory the `vendor` directory isn't needed in this project because it doesn't contain any binary that needs to be built.

If other project depends on this, then its dependency management tool (dep, for example) will take care of putting the required dependencies in the `vendor` directory of that project.

Am I missing something?

**Comment by zgalor** [comment]
I am not sure what is the proper practice when it comes to packages, but `go build` fails without it.
Also, dep allows us to control the dependency version. It may not be needed now, but might be in the future with other packages

**Comment by jhernand** [comment]
I think that it may make sense to include the `Gopkg.toml ` file, but only if we need a version of a dependency that has a semantic versioning practice. In that case the dependency manager of the projects that use this project will load that file, and honour the restriction. But that isn't our case, our only dependency currently is `glog`, and it doesn't use semantic versioning. So I'd say that we should not include any of this in this project.

**Comment by zgalor** [comment]
ok. I will close this PR and remove the commit from #5

**Comment by jhernand** [comment]
As for the failure to run `go bulid`, I think we can include in the `README.md` file some instructions explaining that `glog` is needed, so the user needs to run `go get github.com/golang/glog`.

We should also consider adding a `Log` interface to make the code independent of the underlying logging mechanism.

**Pull request closed without merging**
