### PR TITLE
Check API availability before Authenticating

### LINKED ISSUE #16: Test the available AWX API before attempting to authenticate against it.
See [#24](https://github.com/openshift/autoheal/issues/25#issuecomment-377953555).

Replaces https://github.com/openshift/autoheal/issues/29

### PR DESCRIPTION
**Pull request by moolitayer**
Currently checking availability using a HEAD request to /api/o

I did not add here:
- the ability for HEAD requests with a query component
- The ability for GET or POST to use a different prefix other then /api/v2

They can be added when they are needed.

Fix #16

### CODE REVIEW

**Comment by moolitayer** [comment]
@cben @yaacov @rooftopcellist PTAL

**Review by yaacov — APPROVED** [review]
LGTM :+1:

**Comment by moolitayer** [comment]
@cben @rooftopcellist @jhernand PTAL

**Review by jhernand — APPROVED** [review]

**Comment by moolitayer** [comment]
Thanks @yaacov @jhernand

**Pull request merged**
