### PR TITLE
Rename methods

### LINKED ISSUE #22: Rename Url() to URL()
First mentioned in https://github.com/moolitayer/awx-client-go/pull/19#discussion_r185718683

### PR DESCRIPTION
**Pull request by moolitayer**
Fix #22 

This PR changes the client interface, callers must update to accommodate for it.

### CODE REVIEW

**Review by cben — APPROVED** [review]
/lgtm
Consistent with https://github.com/golang/go/wiki/CodeReviewComments#initialisms

Don't forget to update README (#19).

**Comment by cben** [comment]
https://github.com/golang/go/wiki/CodeReviewComments#initialisms also says:

> This rule also applies to "ID" when it is short for "identifier", so write "appID" instead of "appId".

**Review by jhernand — APPROVED** [review]

**Comment by moolitayer** [comment]
Updated docs for README.md changes.

**Review by zgalor — APPROVED** [review]
/lgtm

**Pull request merged**
